# Generated by Django 4.2.6 on 2023-11-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('type_plan', models.CharField(max_length=250, verbose_name='Tipo')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'Plan',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('type_test', models.IntegerField(verbose_name='tipo')),
                ('minimum_score', models.IntegerField(verbose_name='Puntaje_mínimo')),
                ('maximum_score', models.IntegerField(verbose_name='Puntaje_máximo')),
                ('low_minimum_score', models.IntegerField(verbose_name='Puntaje_mínimo_bajo')),
                ('low_maximum_score', models.IntegerField(verbose_name='Puntaje_máximo_bajo')),
                ('medium_minimum_score', models.IntegerField(verbose_name='Puntaje_mínimo_medio')),
                ('medium_maximum_score', models.IntegerField(verbose_name='Puntaje_máximo_medio')),
                ('high_minimum_score', models.IntegerField(verbose_name='Puntaje_mínimo_alto')),
                ('high_maximum_score', models.IntegerField(verbose_name='Puntaje_máximo_alto')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
                'db_table': 'Test',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30, unique=True, verbose_name='Nombres')),
                ('last_names', models.CharField(max_length=30, unique=True, verbose_name='Apellidos')),
                ('email', models.TextField(max_length=500, verbose_name='Correo')),
                ('username', models.CharField(max_length=30, verbose_name='Nombre_de_usuario')),
                ('identification', models.IntegerField(verbose_name='Identificación')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acondicionamiento_fisico.plan')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'Perfil',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('amount', models.IntegerField(verbose_name='Cantidad')),
                ('seconds', models.IntegerField(verbose_name='Segundos')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acondicionamiento_fisico.plan')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'ejercicio',
                'ordering': ['id'],
            },
        ),
    ]
