# Generated by Django 4.2.6 on 2023-11-06 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acondicionamiento_fisico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('type_plan', models.CharField(max_length=250, verbose_name='Tipo')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Planes',
                'db_table': 'Plan',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='test',
            old_name='type',
            new_name='type_test',
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(max_length=250, verbose_name='Descripción')),
                ('amount', models.IntegerField(verbose_name='Categoría')),
                ('seconds', models.IntegerField(verbose_name='Tipo')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acondicionamiento_fisico.plan')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'db_table': 'ejercicio',
                'ordering': ['id'],
            },
        ),
    ]
