# Generated by Django 4.2.6 on 2023-11-28 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_championship', models.CharField(max_length=30, verbose_name='Nombre_campeonato')),
                ('mode', models.CharField(max_length=30, verbose_name='Modo')),
                ('category', models.CharField(max_length=30, verbose_name='Categoria')),
                ('address', models.CharField(max_length=30, verbose_name='Direccion')),
                ('amount_of_equipments', models.IntegerField(verbose_name='cantidad_de_equipos')),
            ],
            options={
                'verbose_name': 'Campeonato',
                'verbose_name_plural': 'Campeonatos',
                'db_table': 'campeonato',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
                ('equipment_1', models.CharField(max_length=30, unique=True, verbose_name='Equipo_1')),
                ('equipment_2', models.CharField(max_length=30, unique=True, verbose_name='Equipo_2')),
                ('address', models.CharField(max_length=30, verbose_name='Direccion')),
            ],
            options={
                'verbose_name': 'Programación',
                'verbose_name_plural': 'Programaciones',
                'db_table': 'programación',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
                ('inscription', models.CharField(max_length=30, verbose_name='Inscripcion')),
                ('color_equipment', models.CharField(max_length=30, verbose_name='Color_equipacion')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'equipo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('identification', models.IntegerField(verbose_name='Identificacion')),
                ('dorsal', models.IntegerField(verbose_name='Dorsal')),
                ('age', models.IntegerField(verbose_name='Edad')),
                ('contact_number', models.IntegerField(verbose_name='Numero de contacto')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campeonatos.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugador',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='fecha')),
                ('category', models.CharField(max_length=30, verbose_name='Categoría')),
                ('equipment_1', models.CharField(max_length=30, unique=True, verbose_name='Equipo_1')),
                ('equipment_2', models.CharField(max_length=30, unique=True, verbose_name='Equipo_2')),
                ('team_goals1', models.IntegerField(null=True, verbose_name='Goles Equipo 1')),
                ('player_frame_goal_team1', models.CharField(max_length=30, null=True, verbose_name='Jugador que marcó Gol Equipo 1')),
                ('team_goals2', models.IntegerField(null=True, verbose_name='Goles Equipo 2')),
                ('player_frame_goal_team2', models.CharField(max_length=30, null=True, verbose_name='Jugador que marcó Gol Equipo 2')),
                ('result', models.CharField(max_length=30, null=True, verbose_name='Resultado')),
                ('fouls_committed_team1', models.IntegerField(null=True, verbose_name='Faltas Cometidas Equipo 1')),
                ('fouls_committed_team2', models.IntegerField(null=True, verbose_name='Faltas Cometidas Equipo 2')),
                ('yellow_cards_team1', models.IntegerField(null=True, verbose_name='Tarjetas Amarillas Equipo 1')),
                ('yellow_cards_team2', models.IntegerField(null=True, verbose_name='Tarjetas Amarillas Equipo 2')),
                ('red_cards_team1', models.IntegerField(null=True, verbose_name='Tarjetas Rojas Equipo 1')),
                ('red_cards_team2', models.IntegerField(null=True, verbose_name='Tarjetas Rojas Equipo 2')),
                ('payment_arbitration_team1', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pago Arbitraje Equipo 1')),
                ('payment_arbitration_team2', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pago Arbitraje Equipo 2')),
                ('programming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Campeonatos.programming')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'db_table': 'partido',
                'ordering': ['id'],
            },
        ),
    ]
